[pytest]

addopts =
    -v
    -s
    --maxfail=50
    --tb=short
    --headed
    --slowmo=2000


testpaths = tests
python_files = test_*.py

markers =
    param: parametrize validation tests
    smoke: critical tests
    regression: full testing

filterwarnings = ignore::pytest.PytestUnknownMarkWarning